### ISSUE TITLE
[EPIC]Configure Initial Kubernetes Cluster

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/infrastructure#1]
Description:
We need to configure the initial Kubernetes cluster using Rancher as per the group decision. 
We have two separate VPS servers that can be used for the config and nodes.

Subtasks:
- [x] setup the repo folder structure
- [ ] add the initial Rancher config in the repo: #2 [Install Rancher](https://github.com/podkrepi-bg/infrastructure/issues/2)
- [ ] update the README and CONTRIBUTE with relevant instructions how to add more services
- [ ] create at list two issues with next steps

**Comment by imilchev** [comment]
done
