### ISSUE TITLE
[Feature] Configure KeyCloak as IdentityProvider with local database

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/infrastructure#6]
**Is your feature request related to a problem? Please describe.**
We need IdentityProdiver service, for enabling User registration/Authentication/Authorization and RBAC for the functionality of the system.

**Describe the solution you'd like**
We should start with Keycloak as the most popular solution as per the discussion here: https://github.com/podkrepi-bg/frontend/discussions/259.  If we hit a major problem we can switch to another since the feature support is quite the similar.

**Additional context**
Main requirement for the IdentityProvider is the cost to not depend on count of users or the requests, which is the usual pricing of the popular Authentication providers(OKTA, Auth0). To achieve this we want to use open-source solution with the database hosted on our servers.

**Tasks to complete** 
- [ ] add Keycloak to docker-compose.yml until Kubernetes config is ready
- [x] add Keycloak to Kubernetes config
- [ ] Setup email sent from Keycloak [here](https://keycloak-dev.podkrepi.bg/auth/admin/master/console/#/realms/master/smtp-settings)
